alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"
alias dcub="docker compose up --no-color --no-log-prefix | npx bunyan"
alias kc="kubectl"
alias tf="terraform"
alias thinker='echo "https://media.giphy.com/media/d3mlE7uhX8KFgEmY/giphy.gif" | xclip -sel clip -i'
alias sully='echo "https://i.kym-cdn.com/entries/icons/original/000/032/390/sully.png" | xclip -sel clip -i'
alias plz="sudo"
alias docker-compose="docker compose"
